# /cilium/helmrelease-cilium.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      version: v1.15.4
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: -1 # keep trying to remediate
    crds: CreateReplace # Upgrade CRDs on package update
  releaseName: cilium
  valuesFrom:
  - kind: ConfigMap
    name: cilium-helm-values
    valuesKey: values.yaml